services:
  next-app:
    container_name: next-app
    build:
      context: .
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-https://techno-comfort.pro}
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
